Iniciamos a análise importando a biblioteca do Python Pandas e o Numpy.
Em seguida carregamos a nossa base de dados em formato de csv

In [29]:
import pandas as pd
import numpy as np

df_vendas_eventos = pd.read_csv("vendas_eventos.csv", encoding='latin1', sep=";", low_memory = False)

#Visualização inicial
display(df_vendas_eventos.head(10))

#Verificando colunas
display(list(df_vendas_eventos.columns))

#Exibindo informações da tabela
display(df_vendas_eventos.info())

#Descrevendo informações como: média, mínimo, máximo
display(df_vendas_eventos.describe())

      evento        data tipo_cliente  ingressos_vendidos  valor_ingresso
0   Carnaval  15/02/2025        Sócio                 300             180
1   Carnaval  15/02/2025    Não Sócio                 320             200
2     Páscoa  20/04/2025        Sócio                 200             120
3     Páscoa  20/04/2025    Não Sócio                 200             140
4   São João  24/06/2025        Sócio                 350             180
5   São João  24/06/2025    Não Sócio                 300             200
6      Natal  24/12/2025        Sócio                 250             190
7      Natal  24/12/2025    Não Sócio                 320             210
8  Reveillon  31/12/2025        Sócio                 350             200
9  Reveillon  31/12/2025    Não Sócio                 330             220

['evento', 'data', 'tipo_cliente', 'ingressos_vendidos', 'valor_ingresso']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   evento              10 non-null     object
 1   data                10 non-null     object
 2   tipo_cliente        10 non-null     object
 3   ingressos_vendidos  10 non-null     int64
 4   valor_ingresso      10 non-null     int64
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

None

       ingressos_vendidos  valor_ingresso
count           10.000000       10.000000
mean           292.000000      184.000000
std             56.332347       31.340425
min            200.000000      120.000000
25%            262.500000      180.000000
50%            310.000000      195.000000
75%            327.500000      200.000000
max            350.000000      220.000000

Tratamento de dados:

In [34]:
#Transformando para o formato de "pd.to_datetime": ano, mês e dia

df_vendas_eventos["data"]= pd.to_datetime(df_vendas_eventos["data"], format= "%d/%m/%Y")
display(df_vendas_eventos)

      evento       data tipo_cliente  ingressos_vendidos  valor_ingresso
0   Carnaval 2025-02-15        Sócio                 300             180
1   Carnaval 2025-02-15    Não Sócio                 320             200
2     Páscoa 2025-04-20        Sócio                 200             120
3     Páscoa 2025-04-20    Não Sócio                 200             140
4   São João 2025-06-24        Sócio                 350             180
5   São João 2025-06-24    Não Sócio                 300             200
6      Natal 2025-12-24        Sócio                 250             190
7      Natal 2025-12-24    Não Sócio                 320             210
8  Reveillon 2025-12-31        Sócio                 350             200
9  Reveillon 2025-12-31    Não Sócio                 330             220

Criando uma nova coluna chamada "faturamento" para calcularmos o valor total do faturamento dos eventos

In [36]:
df_vendas_eventos["faturamento"] = df_vendas_eventos["ingressos_vendidos"] * df_vendas_eventos["valor_ingresso"]

display(df_vendas_eventos)

,evento,data,tipo_cliente,ingressos_vendidos,valor_ingresso,faturamento
0,Carnaval,2025-02-15,Sócio,300,180,54000
1,Carnaval,2025-02-15,Não Sócio,320,200,64000
2,Páscoa,2025-04-20,Sócio,200,120,24000
3,Páscoa,2025-04-20,Não Sócio,200,140,28000
4,São João,2025-06-24,Sócio,350,180,63000
5,São João,2025-06-24,Não Sócio,300,200,60000
6,Natal,2025-12-24,Sócio,250,190,47500
7,Natal,2025-12-24,Não Sócio,320,210,67200
8,Reveillon,2025-12-31,Sócio,350,200,70000
9,Reveillon,2025-12-31,Não Sócio,330,220,72600

Nesta parte, iremos agrupar valores de colunas semelhantes, selecionamos as colunas utilizando o "groupby": evento. Em seguida, calculamos a soma total desses faturamento utilizando a função "sum()". Também ordenamos os valores dos faturamentos ( do maior para o menor).

In [38]:
faturamento_evento = df_vendas_eventos.groupby("evento")["faturamento"].sum()
faturamento_evento = faturamento_evento.sort_values(ascending=False)
display(faturamento_evento)

evento
Reveillon    142600
São João     123000
Carnaval     118000
Natal        114700
Páscoa        52000
Name: faturamento, dtype: int64